---
AllCops:
  Excludes:
    - vendor/**
ClassLength:
  Max: 200
ClassVars:
  Enabled: false
CyclomaticComplexity:
  Max: 10
Documentation:
  Enabled: false
EmptyLinesAroundBody:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 25
ParameterLists:
  Max: 6
